var Englishworddic = 
[
"replenishment lead time",
"shipment point",
"shipping point",
"pick time",
"pack time",
"factory calendar",
"plant maintenance (PM)",
"authorization administration",
"authorization management",
"access management",
"process rights",
"route",
"transit time transit period",
"daily work",
"daily tasks",
"authorization role",
"company code",
"to lock",
"to block",
"to disable",
"to deactivate",
"to unlock",
"to enable",
"to activate",
"to unblock",
"maternity protection (maternity leave)",
"maternity leave",
"parental Leave",
"infotype",
"additional costs",
"extra charges",
"extra costs",
"surcharges",
"article",
"item",
"assortment"
];

var Germanworddic = 
[
"Wiederbeschaffungszeit (f)",
"Versandstelle (f)",
"Versandstelle (f)",
"Richtzeit (f)",
"Richtzeit (f)",
"Fabrikkalender (m)",
"Instandhaltung (f)",
"Berechtigungsverwaltung (f)",
"Berechtigungsverwaltung (f)",
"Berechtigungsverwaltung (f)",
"Prozessrechte (f)",
"Route (f)",
"Transitzeitraum (m)",
"Tägliche Arbeiten (f)",
"Tägliche Arbeiten (f)",
"Berechtigungsrolle (f)",
"Buchungskreis (m)",
"sperren",
"sperren",
"sperren",
"sperren",
"entsperren",
"entsperren",
"entsperren",
"entsperren",
"Mutterschutz (m)",
"Mutterschutz (m)",
"Erziehungsurlaub (m)",
"Infotyp (m)",
"Mehrkosten (f)",
"Mehrkosten (f)",
"Mehrkosten (f)",
"Mehrkosten (f)",
"Artikel (m)",
"Artikel (m)",
"Sortiment (n)"
];
autocomplete(document.getElementById("myInput"), Englishworddic);